//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdplorerProject.AdplorerAPIServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1", ConfigurationName="AdplorerAPIServiceReference.CustomerWSSoap")]
    public interface CustomerWSSoap {
        
        // CODEGEN : La génération du contrat de message depuis le message CreateCustomerWSRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://www.publocity.de/ns/Customer_1_1/CreateCustomerWS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DtoBase))]
        AdplorerProject.AdplorerAPIServiceReference.CreateCustomerWSResponse CreateCustomerWS(AdplorerProject.AdplorerAPIServiceReference.CreateCustomerWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.publocity.de/ns/Customer_1_1/CreateCustomerWS", ReplyAction="*")]
        System.Threading.Tasks.Task<AdplorerProject.AdplorerAPIServiceReference.CreateCustomerWSResponse> CreateCustomerWSAsync(AdplorerProject.AdplorerAPIServiceReference.CreateCustomerWSRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message UpdateCustomerWSRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://www.publocity.de/ns/Customer_1_1/UpdateCustomerWS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DtoBase))]
        AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerWSResponse UpdateCustomerWS(AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.publocity.de/ns/Customer_1_1/UpdateCustomerWS", ReplyAction="*")]
        System.Threading.Tasks.Task<AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerWSResponse> UpdateCustomerWSAsync(AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerWSRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message GetCustomersByQueryWSRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="http://www.publocity.de/ns/Customer_1_1/GetCustomersByQueryWS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DtoBase))]
        AdplorerProject.AdplorerAPIServiceReference.GetCustomersByQueryWSResponse GetCustomersByQueryWS(AdplorerProject.AdplorerAPIServiceReference.GetCustomersByQueryWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.publocity.de/ns/Customer_1_1/GetCustomersByQueryWS", ReplyAction="*")]
        System.Threading.Tasks.Task<AdplorerProject.AdplorerAPIServiceReference.GetCustomersByQueryWSResponse> GetCustomersByQueryWSAsync(AdplorerProject.AdplorerAPIServiceReference.GetCustomersByQueryWSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public partial class PartialError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long primaryIDField;
        
        private long secondaryIDField;
        
        private string messageField;
        
        private PartialErrorLevel errorLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long PrimaryID {
            get {
                return this.primaryIDField;
            }
            set {
                this.primaryIDField = value;
                this.RaisePropertyChanged("PrimaryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long SecondaryID {
            get {
                return this.secondaryIDField;
            }
            set {
                this.secondaryIDField = value;
                this.RaisePropertyChanged("SecondaryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PartialErrorLevel ErrorLevel {
            get {
                return this.errorLevelField;
            }
            set {
                this.errorLevelField = value;
                this.RaisePropertyChanged("ErrorLevel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public enum PartialErrorLevel {
        
        /// <remarks/>
        Other,
        
        /// <remarks/>
        Campaign,
        
        /// <remarks/>
        GeoLocation,
        
        /// <remarks/>
        Company,
        
        /// <remarks/>
        Order,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public partial class ControlsValidation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] controlsValidatedField;
        
        private string[] controlsNotValidatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] ControlsValidated {
            get {
                return this.controlsValidatedField;
            }
            set {
                this.controlsValidatedField = value;
                this.RaisePropertyChanged("ControlsValidated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] ControlsNotValidated {
            get {
                return this.controlsNotValidatedField;
            }
            set {
                this.controlsNotValidatedField = value;
                this.RaisePropertyChanged("ControlsNotValidated");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetCustomersResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateCustomerResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateCustomerResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public partial class ResponseBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private bool successField;
        
        private int errorCodeField;
        
        private ControlsValidation controlsValidationField;
        
        private PartialError[] partialErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ControlsValidation ControlsValidation {
            get {
                return this.controlsValidationField;
            }
            set {
                this.controlsValidationField = value;
                this.RaisePropertyChanged("ControlsValidation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public PartialError[] PartialErrors {
            get {
                return this.partialErrorsField;
            }
            set {
                this.partialErrorsField = value;
                this.RaisePropertyChanged("PartialErrors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public partial class GetCustomersResponse : ResponseBase {
        
        private CustomerDto[] customerListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Customer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CustomerDto[] CustomerList {
            get {
                return this.customerListField;
            }
            set {
                this.customerListField = value;
                this.RaisePropertyChanged("CustomerList");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public partial class CustomerDto : DtoBase {
        
        private UserDto[] allUsersListField;
        
        private CompanyDto companyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("User", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UserDto[] AllUsersList {
            get {
                return this.allUsersListField;
            }
            set {
                this.allUsersListField = value;
                this.RaisePropertyChanged("AllUsersList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CompanyDto Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public partial class UserDto : DtoBase {
        
        private Salutation salutationField;
        
        private bool salutationFieldSpecified;
        
        private string customerTitleField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string languageField;
        
        private string emailField;
        
        private string phoneField;
        
        private string faxField;
        
        private string externalIDField;
        
        private int agencyIDField;
        
        private bool agencyIDFieldSpecified;
        
        private int userIDField;
        
        private string bCCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Salutation Salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
                this.RaisePropertyChanged("Salutation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalutationSpecified {
            get {
                return this.salutationFieldSpecified;
            }
            set {
                this.salutationFieldSpecified = value;
                this.RaisePropertyChanged("SalutationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CustomerTitle {
            get {
                return this.customerTitleField;
            }
            set {
                this.customerTitleField = value;
                this.RaisePropertyChanged("CustomerTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("Fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ExternalID {
            get {
                return this.externalIDField;
            }
            set {
                this.externalIDField = value;
                this.RaisePropertyChanged("ExternalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int AgencyID {
            get {
                return this.agencyIDField;
            }
            set {
                this.agencyIDField = value;
                this.RaisePropertyChanged("AgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AgencyIDSpecified {
            get {
                return this.agencyIDFieldSpecified;
            }
            set {
                this.agencyIDFieldSpecified = value;
                this.RaisePropertyChanged("AgencyIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string BCC {
            get {
                return this.bCCField;
            }
            set {
                this.bCCField = value;
                this.RaisePropertyChanged("BCC");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public enum Salutation {
        
        /// <remarks/>
        Ms,
        
        /// <remarks/>
        Mr,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerQueryDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanyDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public partial class DtoBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public partial class CustomerQueryDto : DtoBase {
        
        private CustomerQueryItemDto[] queryItemListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("QueryItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CustomerQueryItemDto[] QueryItemList {
            get {
                return this.queryItemListField;
            }
            set {
                this.queryItemListField = value;
                this.RaisePropertyChanged("QueryItemList");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public partial class CustomerQueryItemDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private QueryOperator queryOperatorField;
        
        private string valueField;
        
        private CustomerQueryProperty queryPropertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public QueryOperator QueryOperator {
            get {
                return this.queryOperatorField;
            }
            set {
                this.queryOperatorField = value;
                this.RaisePropertyChanged("QueryOperator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public CustomerQueryProperty QueryProperty {
            get {
                return this.queryPropertyField;
            }
            set {
                this.queryPropertyField = value;
                this.RaisePropertyChanged("QueryProperty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public enum QueryOperator {
        
        /// <remarks/>
        Equals,
        
        /// <remarks/>
        NotEquals,
        
        /// <remarks/>
        Contains,
        
        /// <remarks/>
        GreaterThan,
        
        /// <remarks/>
        GreaterThanOrEquals,
        
        /// <remarks/>
        LessThan,
        
        /// <remarks/>
        LessThanOrEquals,
        
        /// <remarks/>
        BeginsWith,
        
        /// <remarks/>
        EndsWith,
        
        /// <remarks/>
        DateFrom,
        
        /// <remarks/>
        DateTo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public enum CustomerQueryProperty {
        
        /// <remarks/>
        IdAccountingClient,
        
        /// <remarks/>
        CompanyID,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public partial class CompanyDto : DtoBase {
        
        private string idAccountingClientField;
        
        private string companyNameField;
        
        private string companyNameShortField;
        
        private string streetField;
        
        private string zipField;
        
        private string cityField;
        
        private string countryField;
        
        private string phoneField;
        
        private string currencyField;
        
        private string industryBranchField;
        
        private string agencyField;
        
        private string notesField;
        
        private string serviceAgentSalesField;
        
        private string invoiceToField;
        
        private SendInvoiceBy sendInvoiceByField;
        
        private bool sendInvoiceByFieldSpecified;
        
        private string accountNumberField;
        
        private string bankCodeField;
        
        private string bankNameField;
        
        private DirectDebitAuthorization directDebitAuthorizationField;
        
        private bool directDebitAuthorizationFieldSpecified;
        
        private int dateOfPaymentField;
        
        private bool dateOfPaymentFieldSpecified;
        
        private string vatIdentificationNumberField;
        
        private string taxRegionField;
        
        private AdwordsPayment adwordsPaymentField;
        
        private bool adwordsPaymentFieldSpecified;
        
        private string hGKMemberNumberField;
        
        private float discountPercentField;
        
        private bool discountPercentFieldSpecified;
        
        private string tradeFairField;
        
        private string serviceAgentSales2Field;
        
        private RelatedCompany relatedCompanyField;
        
        private bool relatedCompanyFieldSpecified;
        
        private CustomerType customerTypeField;
        
        private bool customerTypeFieldSpecified;
        
        private int agencyIDField;
        
        private bool agencyIDFieldSpecified;
        
        private string mandantIDField;
        
        private string destinationUrlField;
        
        private string placeholder1Field;
        
        private string placeholder2Field;
        
        private string placeholder3Field;
        
        private string placeholder4Field;
        
        private string placeholder5Field;
        
        private string placeholder6Field;
        
        private string placeholder7Field;
        
        private string placeholder8Field;
        
        private int companyIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IdAccountingClient {
            get {
                return this.idAccountingClientField;
            }
            set {
                this.idAccountingClientField = value;
                this.RaisePropertyChanged("IdAccountingClient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CompanyNameShort {
            get {
                return this.companyNameShortField;
            }
            set {
                this.companyNameShortField = value;
                this.RaisePropertyChanged("CompanyNameShort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string IndustryBranch {
            get {
                return this.industryBranchField;
            }
            set {
                this.industryBranchField = value;
                this.RaisePropertyChanged("IndustryBranch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Agency {
            get {
                return this.agencyField;
            }
            set {
                this.agencyField = value;
                this.RaisePropertyChanged("Agency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("Notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ServiceAgentSales {
            get {
                return this.serviceAgentSalesField;
            }
            set {
                this.serviceAgentSalesField = value;
                this.RaisePropertyChanged("ServiceAgentSales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string InvoiceTo {
            get {
                return this.invoiceToField;
            }
            set {
                this.invoiceToField = value;
                this.RaisePropertyChanged("InvoiceTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public SendInvoiceBy SendInvoiceBy {
            get {
                return this.sendInvoiceByField;
            }
            set {
                this.sendInvoiceByField = value;
                this.RaisePropertyChanged("SendInvoiceBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SendInvoiceBySpecified {
            get {
                return this.sendInvoiceByFieldSpecified;
            }
            set {
                this.sendInvoiceByFieldSpecified = value;
                this.RaisePropertyChanged("SendInvoiceBySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("AccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("BankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string BankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
                this.RaisePropertyChanged("BankName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public DirectDebitAuthorization DirectDebitAuthorization {
            get {
                return this.directDebitAuthorizationField;
            }
            set {
                this.directDebitAuthorizationField = value;
                this.RaisePropertyChanged("DirectDebitAuthorization");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DirectDebitAuthorizationSpecified {
            get {
                return this.directDebitAuthorizationFieldSpecified;
            }
            set {
                this.directDebitAuthorizationFieldSpecified = value;
                this.RaisePropertyChanged("DirectDebitAuthorizationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public int DateOfPayment {
            get {
                return this.dateOfPaymentField;
            }
            set {
                this.dateOfPaymentField = value;
                this.RaisePropertyChanged("DateOfPayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOfPaymentSpecified {
            get {
                return this.dateOfPaymentFieldSpecified;
            }
            set {
                this.dateOfPaymentFieldSpecified = value;
                this.RaisePropertyChanged("DateOfPaymentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string VatIdentificationNumber {
            get {
                return this.vatIdentificationNumberField;
            }
            set {
                this.vatIdentificationNumberField = value;
                this.RaisePropertyChanged("VatIdentificationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string TaxRegion {
            get {
                return this.taxRegionField;
            }
            set {
                this.taxRegionField = value;
                this.RaisePropertyChanged("TaxRegion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public AdwordsPayment AdwordsPayment {
            get {
                return this.adwordsPaymentField;
            }
            set {
                this.adwordsPaymentField = value;
                this.RaisePropertyChanged("AdwordsPayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdwordsPaymentSpecified {
            get {
                return this.adwordsPaymentFieldSpecified;
            }
            set {
                this.adwordsPaymentFieldSpecified = value;
                this.RaisePropertyChanged("AdwordsPaymentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string HGKMemberNumber {
            get {
                return this.hGKMemberNumberField;
            }
            set {
                this.hGKMemberNumberField = value;
                this.RaisePropertyChanged("HGKMemberNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public float DiscountPercent {
            get {
                return this.discountPercentField;
            }
            set {
                this.discountPercentField = value;
                this.RaisePropertyChanged("DiscountPercent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscountPercentSpecified {
            get {
                return this.discountPercentFieldSpecified;
            }
            set {
                this.discountPercentFieldSpecified = value;
                this.RaisePropertyChanged("DiscountPercentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string TradeFair {
            get {
                return this.tradeFairField;
            }
            set {
                this.tradeFairField = value;
                this.RaisePropertyChanged("TradeFair");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string ServiceAgentSales2 {
            get {
                return this.serviceAgentSales2Field;
            }
            set {
                this.serviceAgentSales2Field = value;
                this.RaisePropertyChanged("ServiceAgentSales2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public RelatedCompany RelatedCompany {
            get {
                return this.relatedCompanyField;
            }
            set {
                this.relatedCompanyField = value;
                this.RaisePropertyChanged("RelatedCompany");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RelatedCompanySpecified {
            get {
                return this.relatedCompanyFieldSpecified;
            }
            set {
                this.relatedCompanyFieldSpecified = value;
                this.RaisePropertyChanged("RelatedCompanySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public CustomerType CustomerType {
            get {
                return this.customerTypeField;
            }
            set {
                this.customerTypeField = value;
                this.RaisePropertyChanged("CustomerType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomerTypeSpecified {
            get {
                return this.customerTypeFieldSpecified;
            }
            set {
                this.customerTypeFieldSpecified = value;
                this.RaisePropertyChanged("CustomerTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public int AgencyID {
            get {
                return this.agencyIDField;
            }
            set {
                this.agencyIDField = value;
                this.RaisePropertyChanged("AgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AgencyIDSpecified {
            get {
                return this.agencyIDFieldSpecified;
            }
            set {
                this.agencyIDFieldSpecified = value;
                this.RaisePropertyChanged("AgencyIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string MandantID {
            get {
                return this.mandantIDField;
            }
            set {
                this.mandantIDField = value;
                this.RaisePropertyChanged("MandantID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string DestinationUrl {
            get {
                return this.destinationUrlField;
            }
            set {
                this.destinationUrlField = value;
                this.RaisePropertyChanged("DestinationUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string Placeholder1 {
            get {
                return this.placeholder1Field;
            }
            set {
                this.placeholder1Field = value;
                this.RaisePropertyChanged("Placeholder1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string Placeholder2 {
            get {
                return this.placeholder2Field;
            }
            set {
                this.placeholder2Field = value;
                this.RaisePropertyChanged("Placeholder2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string Placeholder3 {
            get {
                return this.placeholder3Field;
            }
            set {
                this.placeholder3Field = value;
                this.RaisePropertyChanged("Placeholder3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string Placeholder4 {
            get {
                return this.placeholder4Field;
            }
            set {
                this.placeholder4Field = value;
                this.RaisePropertyChanged("Placeholder4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string Placeholder5 {
            get {
                return this.placeholder5Field;
            }
            set {
                this.placeholder5Field = value;
                this.RaisePropertyChanged("Placeholder5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string Placeholder6 {
            get {
                return this.placeholder6Field;
            }
            set {
                this.placeholder6Field = value;
                this.RaisePropertyChanged("Placeholder6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string Placeholder7 {
            get {
                return this.placeholder7Field;
            }
            set {
                this.placeholder7Field = value;
                this.RaisePropertyChanged("Placeholder7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string Placeholder8 {
            get {
                return this.placeholder8Field;
            }
            set {
                this.placeholder8Field = value;
                this.RaisePropertyChanged("Placeholder8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public int CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
                this.RaisePropertyChanged("CompanyID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public enum SendInvoiceBy {
        
        /// <remarks/>
        Letter,
        
        /// <remarks/>
        Email,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public enum DirectDebitAuthorization {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        CreditCardAuthorization,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public enum AdwordsPayment {
        
        /// <remarks/>
        NoPrePayment,
        
        /// <remarks/>
        AdvancePayment,
        
        /// <remarks/>
        AccountWithClient,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public enum RelatedCompany {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Yes,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public enum CustomerType {
        
        /// <remarks/>
        Private,
        
        /// <remarks/>
        Commercial,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public partial class UpdateCustomerResponse : ResponseBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
    public partial class CreateCustomerResponse : ResponseBase {
        
        private CustomerDto customerField;
        
        private int existingUserIDField;
        
        private bool existingUserIDFieldSpecified;
        
        private int existingCompanyIDField;
        
        private bool existingCompanyIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CustomerDto Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int ExistingUserID {
            get {
                return this.existingUserIDField;
            }
            set {
                this.existingUserIDField = value;
                this.RaisePropertyChanged("ExistingUserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExistingUserIDSpecified {
            get {
                return this.existingUserIDFieldSpecified;
            }
            set {
                this.existingUserIDFieldSpecified = value;
                this.RaisePropertyChanged("ExistingUserIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int ExistingCompanyID {
            get {
                return this.existingCompanyIDField;
            }
            set {
                this.existingCompanyIDField = value;
                this.RaisePropertyChanged("ExistingCompanyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExistingCompanyIDSpecified {
            get {
                return this.existingCompanyIDFieldSpecified;
            }
            set {
                this.existingCompanyIDFieldSpecified = value;
                this.RaisePropertyChanged("ExistingCompanyIDSpecified");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateCustomerWS", WrapperNamespace="http://www.publocity.de/ns/Customer_1_1", IsWrapped=true)]
    public partial class CreateCustomerWSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
        public AdplorerProject.AdplorerAPIServiceReference.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1", Order=0)]
        public AdplorerProject.AdplorerAPIServiceReference.CustomerDto CustomerDto;
        
        public CreateCustomerWSRequest() {
        }
        
        public CreateCustomerWSRequest(AdplorerProject.AdplorerAPIServiceReference.AuthHeader AuthHeader, AdplorerProject.AdplorerAPIServiceReference.CustomerDto CustomerDto) {
            this.AuthHeader = AuthHeader;
            this.CustomerDto = CustomerDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateCustomerWSResponse", WrapperNamespace="http://www.publocity.de/ns/Customer_1_1", IsWrapped=true)]
    public partial class CreateCustomerWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1", Order=0)]
        public AdplorerProject.AdplorerAPIServiceReference.CreateCustomerResponse CreateCustomerWSResult;
        
        public CreateCustomerWSResponse() {
        }
        
        public CreateCustomerWSResponse(AdplorerProject.AdplorerAPIServiceReference.CreateCustomerResponse CreateCustomerWSResult) {
            this.CreateCustomerWSResult = CreateCustomerWSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCustomerWS", WrapperNamespace="http://www.publocity.de/ns/Customer_1_1", IsWrapped=true)]
    public partial class UpdateCustomerWSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
        public AdplorerProject.AdplorerAPIServiceReference.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1", Order=0)]
        public AdplorerProject.AdplorerAPIServiceReference.CustomerDto CustomerDto;
        
        public UpdateCustomerWSRequest() {
        }
        
        public UpdateCustomerWSRequest(AdplorerProject.AdplorerAPIServiceReference.AuthHeader AuthHeader, AdplorerProject.AdplorerAPIServiceReference.CustomerDto CustomerDto) {
            this.AuthHeader = AuthHeader;
            this.CustomerDto = CustomerDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCustomerWSResponse", WrapperNamespace="http://www.publocity.de/ns/Customer_1_1", IsWrapped=true)]
    public partial class UpdateCustomerWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1", Order=0)]
        public AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerResponse UpdateCustomerWSResult;
        
        public UpdateCustomerWSResponse() {
        }
        
        public UpdateCustomerWSResponse(AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerResponse UpdateCustomerWSResult) {
            this.UpdateCustomerWSResult = UpdateCustomerWSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomersByQueryWS", WrapperNamespace="http://www.publocity.de/ns/Customer_1_1", IsWrapped=true)]
    public partial class GetCustomersByQueryWSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1")]
        public AdplorerProject.AdplorerAPIServiceReference.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1", Order=0)]
        public AdplorerProject.AdplorerAPIServiceReference.CustomerQueryDto Query;
        
        public GetCustomersByQueryWSRequest() {
        }
        
        public GetCustomersByQueryWSRequest(AdplorerProject.AdplorerAPIServiceReference.AuthHeader AuthHeader, AdplorerProject.AdplorerAPIServiceReference.CustomerQueryDto Query) {
            this.AuthHeader = AuthHeader;
            this.Query = Query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomersByQueryWSResponse", WrapperNamespace="http://www.publocity.de/ns/Customer_1_1", IsWrapped=true)]
    public partial class GetCustomersByQueryWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.publocity.de/ns/Customer_1_1", Order=0)]
        public AdplorerProject.AdplorerAPIServiceReference.GetCustomersResponse GetCustomersByQueryWSResult;
        
        public GetCustomersByQueryWSResponse() {
        }
        
        public GetCustomersByQueryWSResponse(AdplorerProject.AdplorerAPIServiceReference.GetCustomersResponse GetCustomersByQueryWSResult) {
            this.GetCustomersByQueryWSResult = GetCustomersByQueryWSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerWSSoapChannel : AdplorerProject.AdplorerAPIServiceReference.CustomerWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerWSSoapClient : System.ServiceModel.ClientBase<AdplorerProject.AdplorerAPIServiceReference.CustomerWSSoap>, AdplorerProject.AdplorerAPIServiceReference.CustomerWSSoap {
        
        public CustomerWSSoapClient() {
        }
        
        public CustomerWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdplorerProject.AdplorerAPIServiceReference.CreateCustomerWSResponse AdplorerProject.AdplorerAPIServiceReference.CustomerWSSoap.CreateCustomerWS(AdplorerProject.AdplorerAPIServiceReference.CreateCustomerWSRequest request) {
            return base.Channel.CreateCustomerWS(request);
        }
        
        public AdplorerProject.AdplorerAPIServiceReference.CreateCustomerResponse CreateCustomerWS(AdplorerProject.AdplorerAPIServiceReference.AuthHeader AuthHeader, AdplorerProject.AdplorerAPIServiceReference.CustomerDto CustomerDto) {
            AdplorerProject.AdplorerAPIServiceReference.CreateCustomerWSRequest inValue = new AdplorerProject.AdplorerAPIServiceReference.CreateCustomerWSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.CustomerDto = CustomerDto;
            AdplorerProject.AdplorerAPIServiceReference.CreateCustomerWSResponse retVal = ((AdplorerProject.AdplorerAPIServiceReference.CustomerWSSoap)(this)).CreateCustomerWS(inValue);
            return retVal.CreateCustomerWSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdplorerProject.AdplorerAPIServiceReference.CreateCustomerWSResponse> AdplorerProject.AdplorerAPIServiceReference.CustomerWSSoap.CreateCustomerWSAsync(AdplorerProject.AdplorerAPIServiceReference.CreateCustomerWSRequest request) {
            return base.Channel.CreateCustomerWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdplorerProject.AdplorerAPIServiceReference.CreateCustomerWSResponse> CreateCustomerWSAsync(AdplorerProject.AdplorerAPIServiceReference.AuthHeader AuthHeader, AdplorerProject.AdplorerAPIServiceReference.CustomerDto CustomerDto) {
            AdplorerProject.AdplorerAPIServiceReference.CreateCustomerWSRequest inValue = new AdplorerProject.AdplorerAPIServiceReference.CreateCustomerWSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.CustomerDto = CustomerDto;
            return ((AdplorerProject.AdplorerAPIServiceReference.CustomerWSSoap)(this)).CreateCustomerWSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerWSResponse AdplorerProject.AdplorerAPIServiceReference.CustomerWSSoap.UpdateCustomerWS(AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerWSRequest request) {
            return base.Channel.UpdateCustomerWS(request);
        }
        
        public AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerResponse UpdateCustomerWS(AdplorerProject.AdplorerAPIServiceReference.AuthHeader AuthHeader, AdplorerProject.AdplorerAPIServiceReference.CustomerDto CustomerDto) {
            AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerWSRequest inValue = new AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerWSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.CustomerDto = CustomerDto;
            AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerWSResponse retVal = ((AdplorerProject.AdplorerAPIServiceReference.CustomerWSSoap)(this)).UpdateCustomerWS(inValue);
            return retVal.UpdateCustomerWSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerWSResponse> AdplorerProject.AdplorerAPIServiceReference.CustomerWSSoap.UpdateCustomerWSAsync(AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerWSRequest request) {
            return base.Channel.UpdateCustomerWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerWSResponse> UpdateCustomerWSAsync(AdplorerProject.AdplorerAPIServiceReference.AuthHeader AuthHeader, AdplorerProject.AdplorerAPIServiceReference.CustomerDto CustomerDto) {
            AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerWSRequest inValue = new AdplorerProject.AdplorerAPIServiceReference.UpdateCustomerWSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.CustomerDto = CustomerDto;
            return ((AdplorerProject.AdplorerAPIServiceReference.CustomerWSSoap)(this)).UpdateCustomerWSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdplorerProject.AdplorerAPIServiceReference.GetCustomersByQueryWSResponse AdplorerProject.AdplorerAPIServiceReference.CustomerWSSoap.GetCustomersByQueryWS(AdplorerProject.AdplorerAPIServiceReference.GetCustomersByQueryWSRequest request) {
            return base.Channel.GetCustomersByQueryWS(request);
        }
        
        public AdplorerProject.AdplorerAPIServiceReference.GetCustomersResponse GetCustomersByQueryWS(AdplorerProject.AdplorerAPIServiceReference.AuthHeader AuthHeader, AdplorerProject.AdplorerAPIServiceReference.CustomerQueryDto Query) {
            AdplorerProject.AdplorerAPIServiceReference.GetCustomersByQueryWSRequest inValue = new AdplorerProject.AdplorerAPIServiceReference.GetCustomersByQueryWSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.Query = Query;
            AdplorerProject.AdplorerAPIServiceReference.GetCustomersByQueryWSResponse retVal = ((AdplorerProject.AdplorerAPIServiceReference.CustomerWSSoap)(this)).GetCustomersByQueryWS(inValue);
            return retVal.GetCustomersByQueryWSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdplorerProject.AdplorerAPIServiceReference.GetCustomersByQueryWSResponse> AdplorerProject.AdplorerAPIServiceReference.CustomerWSSoap.GetCustomersByQueryWSAsync(AdplorerProject.AdplorerAPIServiceReference.GetCustomersByQueryWSRequest request) {
            return base.Channel.GetCustomersByQueryWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdplorerProject.AdplorerAPIServiceReference.GetCustomersByQueryWSResponse> GetCustomersByQueryWSAsync(AdplorerProject.AdplorerAPIServiceReference.AuthHeader AuthHeader, AdplorerProject.AdplorerAPIServiceReference.CustomerQueryDto Query) {
            AdplorerProject.AdplorerAPIServiceReference.GetCustomersByQueryWSRequest inValue = new AdplorerProject.AdplorerAPIServiceReference.GetCustomersByQueryWSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.Query = Query;
            return ((AdplorerProject.AdplorerAPIServiceReference.CustomerWSSoap)(this)).GetCustomersByQueryWSAsync(inValue);
        }
    }
}
